### ISSUE TITLE
Server.HTTP

### ISSUE THREAD

**Issue by ronimizy** [is-tech-y24-1/Do-Svyazi.Message#7]
## Dependencies
- #4 
- #6 

## Description

Реализовать эндпоинты и middleware для HTTP части сервера

### Эндпоинты

- Получение стейта по айди чата
- Получение количества непрочитанных пользователем сообщений

### Middleware

- Для аутентификации пользователя
Отправить квери для аутентификации
Добавить пользователя к HttpContext 
Сделать extension метод для того чтобы его оттуда доставать
- Для обработки эксепшенов
Выполняет следующий элемент в цепи в try-catch
Ловит application ошибки, соотвествующие HTTP кодам, записывает их в респонс
Ловит базовый эксепшн, записывает в респонс как 500

**Comment by luck-o-o-luck** [comment]
### Для удобства и разделения использую три ветки: одна общая с названием данной ишуи (7-server.HTTP) - в неё я планирую мерджить дочерние ишуи (разделила всю ишую на две части). Как только закрою обе дочерние ишуи, получу апрув, закину пр, где вмерджу в мастер.
